# Generated by Django 4.2.29 on 2026-04-10 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=500, verbose_name='Ifoda')),
                ('result', models.CharField(max_length=200, verbose_name='Natija')),
                ('calculation_type', models.CharField(choices=[('basic', 'Oddiy'), ('advanced', 'Oliy matematika')], default='basic', max_length=20, verbose_name='Tur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hisoblash',
                'verbose_name_plural': 'Hisoblashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
